all:
	g++ -Wall -Werror -ansi -pedantic -o fd_demo fd_code.cpp
	g++ -Wall -Werror -ansi -pedantic -o dir_demo dir_code.cpp

fd: 
	g++ -Wall -Werror -ansi -pedantic -o fd_demo fd_code.cpp

dir: 
	g++ -ansi -pedantic -Wall -Werror -o dir_demo dir_code.cpp
