#!/bin/bash

COUNTER=0
for empty in $( cat < ./githubp/res/$1?tab=repositories |  grep -A1 '<span class="octicon octicon-git-branch"></span>' | sed 's/<span class="octicon octicon-git-branch">.*//g' | sed 's/--//g' | sed 's/,//g' )
do
    let COUNTER=COUNTER+10#$empty
done

echo ,$COUNTER
