#!/usr/bin/perl

$opt_l = "cc";   # default language is c++
$opt_f = "*.cpp";
$opt_a = 0;
$opt_m = 10;
$opt_x = 0;
$opt_c = 0;
$opt_n = 1000;
$bindex = 0; 
$opt_t = 1;

$usage = "moss_run -a <assn.no> [-f <filename>] [OPTIONS]";
$help = "\tUse 'moss_run -h' for help.\n";


while (@ARGV && ($_ = $ARGV[0]) =~ /^-(.)(.*)/) {
	($first,$rest) = ($1,$2);	

	shift(@ARGV);
	if ($first eq "a") {
		if($rest eq '') {
			die "No argument for option -a.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_a = $rest;
		next;
	}	
	if ($first eq "f") {
		if($rest eq '') {
			die "No argument for option -f.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_f = $rest;
		next;
	}

	if ($first eq "b") {
		if($rest eq '') {
			die "No argument for option -b.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_b[$bindex++] = $rest;
		next;
	}

	if ($first eq "m") {
		if($rest eq '') {
			die "No argument for option -m.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_m = $rest;
		next;
	}
	if ($first eq "c") {
		if($rest eq '') {
			die "No argument for option -c.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_c = $rest;
		next;
	}
	if ($first eq "n") {
		if($rest eq '') {
			die "No argument for option -n.\n$help" unless @ARGV;
			$rest = shift(@ARGV);
		}
		$opt_n = $rest;
		next;
	}
	if ($first eq "x") {
		$opt_x = 1;
		next;
	}
	if ($first eq "t") {
		$opt_t = 0;
		next;
	}
	

	if ($first eq "h") {
		print "\nUSAGE:\n\t$usage\n\nOPTIONS:\n\n";
		print "\t-a <assn. no>:\t Assingment number.\n";
		print "\t-f <file name>:\t files to be compared. Default is \"*.cpp\"\n";
		print "\t-l <language>:\t Language. Default value is C++ (cc)\n";
		print "\t Other options are -m -c -b -x. Same as moss_script.\n";

		print "\nEXAMPLES:\n\n";
		print "\t- To compare all (.cpp) files in assingment 4\n";
		print "\t\tmoss_run -a 4\n";
		print "\t- To compare only date.cpp in assingment 2\n";
		print "\t\tmoss_run -a 2 -f date.cpp\n\n";

		exit;
	}

	die "Unrecognized option -$first.  $usage\n$help"; 
}

if($opt_a eq '0'){
	die "Assignment number is not specified.\n$help";
}

$flg_l = " -l ";
if($opt_l eq 0){
	$opt_l ="";
	$flg_l ="";
}

$flg_b = " -b ";
$b_str = "";
if($bindex eq 0){
	$opt_b ="";
	$flg_b ="";
}
else{
	while($bindex!=0){
		$b_str = $b_str . $opt_b[--$bindex];
	}
}
$flg_x = " -x ";
if($opt_x eq  0){
	$flg_x ="";
}
$flg_c = " -c ";
if($opt_c eq 0){
	$opt_c ="";
	$flg_c ="";
}
$flg_m = " -m ";
if($opt_m eq 10){
	$opt_m ="";
	$flg_m ="";
}

$run_command = "source/moss_script" . $flg_l . $opt_l . $flg_c . $opt_c . $flg_m . $opt_m . $flg_x . $flg_b . $b_str . " -n " . $opt_n . " -d /courses/cs012/*/submissions/graded/assn" . $opt_a . "/*/" . $opt_f . "";
print "MOSS is called with:\n\t" . $run_command . "\n";
if($opt_t eq 1){
	system($run_command);
}


